punishments:
  xray:
    item: DIAMOND_ORE
    name: "&cXRay"
    actions:
      ban:
        item: REDSTONE_BLOCK
        display: "&4Ban"
        times:
          1d:
            display: "&a1 Day"
          1w:
            display: "&a1 Week"
          1mo:
            display: "&a1 Month"
          permanent:
            display: "&cPermanent"
      mute:
        item: NOTE_BLOCK
        display: "&6Mute"
        times:
          1d:
            display: "&a1 Day"
          1w:
            display: "&a1 Week"
          1mo:
            display: "&a1 Month"
          permanent:
            display: "&cPermanent"
      warn:
        item: PAPER
        display: "&eWarn"
        times: {}
      kick:
        item: BARRIER
        display: "&cKick"
        times: {}
  hacks:
    item: DIAMOND_SWORD
    name: "&cHacks"
    actions:
      ban:
        item: REDSTONE_BLOCK
        display: "&4Ban"
        times:
          1d:
            display: "&a1 Day"
          1w:
            display: "&a1 Week"
          1mo:
            display: "&a1 Month"
          permanent:
            display: "&cPermanent"
history:
  item: BOOK
  name: "&bHistory"
